name: CI Algorithm notification

on:
  push:
    branches: 
      - "main"
  pull:
    branches:
      - "main"

  # sets permissions of GITHUB_TOKEN  to allow deployment
  permissions:
    contents: read
    pages: write
    id-token: write

  # reuse workflow
  workflow_call:
    inputs:
      username:
        description: "Username call workflow"
        default: "Bes Anh"
        required: true
        type: string
      label:
        description: "Label call workflow"
        default: "test"
        required: false
        type: string

    # Map the workflow outputs to job outputs
    outputs:
      username:
        description: "first job output"
        value: ${{jobs.my_job.outputs.job_ouput1}}
      label:
        description: "second job output"
        value: ${{jobs.my_job.outputs.job_ouput2}}

jobs:
  print-username:
    runs-on: besanh-cicd
    steps:
      - name: Print input name to STDOUT
        run: |
          echo username is: ${{inputs.username}}
      - name: Print input label to STDOUT
        run: |
          echo label is: ${{inputs.label}}
  notify:
    runs-on: besanh-cicd
    steps:
      - name: Notification CI
        uses: appleboy/telegram-action@master
        with:
          to: ${{secrets.TELEGRAM_TO}}
          token: ${{secrets.TELEGRAM_TOKEN}}
          message: |
            Repo: [Commit link]https://github.com/${{github.repository}}${{github.repository}}
            Actor: ${{github.actor}}
            Commit change:
              ${{github.event.commits[0].message}}
            See changes:
              https://github.com/${{github.repository}}/commit/${{github.sha}}
            Action:
              [Commit link]https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
