name: CI Algorithm notification of Leetcode

on:
  push:
    branches: 
      - "leetcode"
  pull_request:
    branches:
      - "leetcode"

# sets permissions of GITHUB_TOKEN  to allow deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  notify:
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: Notification CI
        uses: appleboy/telegram-action@master
        with:
          to: ${{secrets.TELEGRAM_TO}}
          token: ${{secrets.TELEGRAM_TOKEN}}
          message: |
            Repo: [Commit link]https://github.com/${{github.repository}}${{github.repository}}
            Actor: ${{github.actor}}
            Commit change:
              ${{github.event.commits[0].message}}
            See changes:
              https://github.com/${{github.repository}}/commit/${{github.sha}}
            Action:
              [Commit link]https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
